version: "3.6"

services:
  planeks_db:
    image: postgres:11
    container_name: planeks_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=planeks
    networks:
      - planeks-network
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data

  planeks_redis:
    image: redis
    container_name: planeks_redis
    networks:
      - planeks-network
    expose:
      - "6379"

  planeks_site:
    image: planeks:latest
    container_name: planeks_site
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=planeks
      - DB_HOST=planeks_db
      - DEBUG=False
    depends_on:
      - planeks_db
    networks:
      - planeks-network
    ports:
      - 41666:8000
    volumes:
      - ${SITE_PATH}:/app
    command: ./entrypoint.sh

networks:
  planeks-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}