# Generated by Django 3.1 on 2020-10-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Last name')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job')),
                ('rec_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'type one'), (2, 'type two'), (3, 'type three'), (4, 'type four')], default=1, verbose_name='Some type')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rec link')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Date of creation')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Some info')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Record owner')),
            ],
        ),
    ]
